### ISSUE TITLE
Additional query fields prefixes data source

### ISSUE THREAD

**Issue by a-d-v** [innovationnorway/terraform-provider-netbox#27]
Would it be possible to support VRF and Family as query field for the netbox_ipam_prefixes Data Source?

Thank you so much

**Comment by joakimhellum** [comment]
@a-d-v have created #28 which adds support for setting `family` and `vrf_id` properties.  Please let us know if you also need support for the `vrf` filter which matches on the VRF object's `rd` (route distinguisher) field.

**Comment by a-d-v** [comment]
Thank you! This is perfect. No need for `rd` filtering from my side.
